- name: types of conditions
  hosts: local
  connection: local
  vars_prompt:
  - name: Number
    prompt: enter the number
    private: false
  tasks:
  - name: testing the number
    ansible.builtin.debug:
      msg: "the given number {{Number}} is greater than 10"
    when: Number | int > 10

  - name: testing the number
    ansible.builtin.debug:
      msg: "the given number {{Number}} is less than 10"
    when: Number | int < 10