- name: check whether user is existed or not
  hosts: web
  tasks:
  - name: check user is created or not
    ansible.builtin.command: id expense
    register: User                      #registers the output of above command
    ignore_errors: true

  - name: print the user details
    ansible.builtin.debug:
      msg: "{{User}}"

  - name: creating the user if not created
    ansible.builtin.command: useradd expense
    when: User.rc != 0