- name: nginx installation based on facts
  hosts: web
  become: yes
  tasks:
  - name: fetch the statistics facts
    ansible.builtin.debug:
      msg: "{{ ansible_facts }}"
  
  - name: install nginx if it is redhat
    ansible.builtin.dnf:
      name: nginx
      state: present
    when: ansible_os_family == "RedHat"

  - name: install nginx if it is debian
    ansible.builtin.apt:
      name: nginx
      state: present
    when: ansible_os_family == "Debian"