- name: prompting the varibales
  hosts: web
  vars_prompt:
  - name: NAME
    prompt: enter the name
    private: false          #false means it is not confidential
  - name: AGE
    prompt: enter the age
    private: true           #true means it is confidential
  - name: BEHAVIOR
    prompt: what kind of behavior?
  tasks:
  - name: variables prompting in progress
    ansible.builtin.debug:
      msg: "my name is {{NAME}}, age is {{AGE}}, behavior is {{BEHAVIOR}}"