- name: checking variable precedence
  hosts: web
  vars:
    NAME: Anil
    Gender: Male
    Race: Asian
  vars_files:
  - vars.yaml
  vars_prompt:
  - name: NAME
    prompt: what is your name?
  - name: Gender
    prompt: What is your gender?
  - name: Race
    prompt: What is your race?
  tasks:
  - name: checking variable preference
    vars:
      NAME: Anil
      Gender: Male
      Race: Asian
    ansible.builtin.debug:
      msg: "what is your name: {{NAME}}, gender: {{Gender}}, race: {{Race}}"
  

  