- name: different types of datatypes
  hosts: local
  connection: local       # when connection is local/localhost, credentials are not required
  vars:
    alphabet: "a to z"
    count: 26
    types:          # list
    - small letters
    - capital letters
    live: true
    tools:          # map/dictionary
      ci: jenkins
      cm: ansible
      cloud: aws
      aws:
      - IAM
      - S3
  tasks:
  - name: variable types
    ansible.builtin.debug:
      msg: "alphabet from {{alphabet}}, total is {{count}}, types are {{types}}, live:{{live}}, tools are {{tools}}"