- name: installing nginx
  hosts: web
  become: yes
  tasks:
  - name: install nginx in node
    ansible.builtin.package:
      name: nginx
      state: present

  - name: start nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes